# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'fernando1989mg'
    scannerMode: 'Other'
    extraProperties: 'sonar.coverage.jacoco.xmlReportPaths=./build/jacoco/test/jacocoTestReport.xml'
- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
- script: ls -l
  displayName: 'listar'
- script: ls build/reports/tests/test
  displayName: 'listar'
- script: ./gradlew test
  displayName: 'run test'
- script: ls build/reports
  displayName: 'listar'
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'