# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  SONAR_TOKEN: d2a640715a569ebddf15d4869e87e3d0b22c0ecf

steps:

- script: ./gradlew build
  displayName: 'build project'
- script: export SONAR_TOKEN=d2a640715a569ebddf15d4869e87e3d0b22c0ecf
  displayName: 'set sonarcloud token'
- script: echo $SONAR_TOKEN
  displayName: 'print var'
- script: ./gradlew sonarqube
  displayName: 'send report to sonarcloud'
  env:
    SONAR_TOKEN: d2a640715a569ebddf15d4869e87e3d0b22c0ecf