trigger:
  branches:
    include:
      - master
pool:
  vmImage: 'Ubuntu-16.04'
steps:
  - checkout: self
    persistCredentials: true
    clean: true
	- task: Gradle@2
	  inputs:
	    workingDirectory: $(system.defaultWorkingDirectory)'
	    gradleWrapperFile: 'gradlew'
	    gradleOptions: '-Xmx3072m'
	    javaHomeOption: 'JDKVersion'
	    jdkVersionOption: '1.8'
	    jdkArchitectureOption: 'x64'
	    publishJUnitResults: true
	    testResultsFiles: '**/TEST-*.xml'
	    tasks: 'build'